import { useLocation, Link } from "react-router-dom";
import { FileText, CheckCircle, AlertTriangle, Activity, Brain } from "lucide-react";

export default function ReportPage() {
  const location = useLocation();
  const report = location.state?.report;

  if (!report) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50">
        <h1 className="text-2xl font-bold text-gray-400">No report data found.</h1>
        <Link to="/" className="mt-4 text-blue-600 hover:underline">Return Home</Link>
      </div>
    );
  }

  // Determine styling based on result
  const isRisk = report.final_result === "RISK_DYSLEXIA";
  const themeColor = isRisk ? "orange" : "green";
  const statusIcon = isRisk ? <AlertTriangle className="w-12 h-12 text-orange-600" /> : <CheckCircle className="w-12 h-12 text-green-600" />;
  const statusTitle = isRisk ? "Risk Detected" : "Low Risk Detected";
  const statusDesc = isRisk 
    ? "Our AI suggests consulting a specialist for further evaluation." 
    : "Great news! The assessment shows standard reading development.";

  return (
    <div className={`min-h-screen bg-${themeColor}-50 py-12 px-4`}>
      <div className="max-w-4xl mx-auto">
        
        {/* HEADER CARD */}
        <div className="bg-white rounded-3xl shadow-xl overflow-hidden mb-8 border-t-8 border-indigo-600">
          <div className="p-8 md:p-12 text-center">
             <div className={`w-24 h-24 bg-${themeColor}-100 rounded-full flex items-center justify-center mx-auto mb-6`}>
                {statusIcon}
             </div>
             <h1 className={`text-4xl font-extrabold text-${themeColor}-700 mb-3`}>{statusTitle}</h1>
             <p className="text-xl text-gray-500 max-w-2xl mx-auto">{statusDesc}</p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          
          {/* 🧠 AI EXPLANATION */}
          <div className="bg-white p-8 rounded-3xl shadow-lg border border-indigo-50">
             <div className="flex items-center gap-3 mb-6">
                <Brain className="w-6 h-6 text-indigo-600" />
                <h2 className="text-2xl font-bold text-gray-800">AI Analysis</h2>
             </div>
             
             <div className="bg-indigo-50 rounded-xl p-6 mb-4">
               <p className="text-gray-700 leading-relaxed font-medium">
                 "{report.message}"
               </p>
             </div>
             <p className="text-sm text-gray-400">
                Generated by Gemini 1.5 Flash based on phonetic alignment and fluency analysis.
             </p>
          </div>

          {/* 📊 LEVEL BREAKDOWN */}
          <div className="bg-white p-8 rounded-3xl shadow-lg border border-gray-100">
             <div className="flex items-center gap-3 mb-6">
                <Activity className="w-6 h-6 text-blue-600" />
                <h2 className="text-2xl font-bold text-gray-800">Performance</h2>
             </div>

             <div className="space-y-4">
                
                
                {/* You can map actual level scores here if you passed them in the report object */}
             </div>
             
             <div className="mt-8">
                <h4 className="font-bold text-sm text-gray-400 uppercase tracking-wider mb-3">Session Logs</h4>
                <div className="h-48 overflow-y-auto bg-gray-900 text-green-400 p-4 rounded-xl font-mono text-xs shadow-inner">
                    {report.logs.map((log, i) => (
                        <div key={i} className="mb-1 border-b border-gray-800 pb-1 last:border-0">
                            &gt; {log}
                        </div>
                    ))}
                </div>
             </div>
          </div>

        </div>

        <div className="mt-12 text-center">
            <Link 
              to="/" 
              className="inline-flex items-center gap-2 bg-gray-900 text-white px-8 py-4 rounded-xl font-bold hover:bg-black transition-transform hover:scale-105"
            >
               <FileText className="w-5 h-5" /> Back to Assessment Hub
            </Link>
        </div>

      </div>
    </div>
  );
}